//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BayWynCouriersPrototype.BayWynServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BayWynServiceReference.IBayWynService")]
    public interface IBayWynService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBayWynService/CheckLogin", ReplyAction="http://tempuri.org/IBayWynService/CheckLoginResponse")]
        int CheckLogin(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBayWynService/CheckLogin", ReplyAction="http://tempuri.org/IBayWynService/CheckLoginResponse")]
        System.Threading.Tasks.Task<int> CheckLoginAsync(string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBayWynServiceChannel : BayWynCouriersPrototype.BayWynServiceReference.IBayWynService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BayWynServiceClient : System.ServiceModel.ClientBase<BayWynCouriersPrototype.BayWynServiceReference.IBayWynService>, BayWynCouriersPrototype.BayWynServiceReference.IBayWynService {
        
        public BayWynServiceClient() {
        }
        
        public BayWynServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BayWynServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BayWynServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BayWynServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CheckLogin(string username, string password) {
            return base.Channel.CheckLogin(username, password);
        }
        
        public System.Threading.Tasks.Task<int> CheckLoginAsync(string username, string password) {
            return base.Channel.CheckLoginAsync(username, password);
        }
    }
}
